### ISSUE TITLE
Issue refreshing Parameters with property gui=False

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/lightparam#1]
When running `refresh_widgets()` in `ParameterGui` class it looks for all the keys in `self.parametrized.params.items()` and for each of them runs `self.param_widgets[key].update_display()`. This throws a `KeyError `if the Parameter instance has `gui=False`, i.e. if it is not a widget. The proposed fix is adding just one line:

```
 def refresh_widgets(self):
        for name in self.parametrized.params.items().keys():
            if name in self.param_widgets:
                self.param_widgets[name].update_display()

```
instead of 

```
 def refresh_widgets(self):
        for name in self.parametrized.params.items().keys():
            self.param_widgets[name].update_display()
```

**Comment by vilim** [comment]
@diegoasua could you please make a PR?
